---
- name: setting up jenkins
  hosts: sys02app02
  become: yes
  tasks:
  - name:  adding jenkins repo adding
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Import a key from a url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  - name: remove the latest version of java
    yum:
      name: java*
      state: absent
  - name: install the latest version of java
    yum:
      name: java-17-openjdk-devel
      state: present
  - name: install the latest version of jenkins
    yum:
      name: jenkins
      state: latest
  - name: Start service jenkins service
    ansible.builtin.service:
      name: jenkins
      state: started
